Combine all agents into one ci.yml
Significant-Gravitas/Auto-GPT-Benchmarks pull request #79
Opened 2023-07-09 23:13 UTC by merwanehamadi

### Background

### Changes

### PR Quality Checklist
- [X] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy .
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports --ignore-pass-after-docstring --in-place agbenchmark
    ```

2023-07-09 23:14 UTC, merwanehamadi commented on .github/workflows/ci.yml
> +    - cron: '0 8 * * *'
We can trigger the CI to test the agents against OpenAI or wait every 8 AM UTC

2023-07-09 23:14 UTC, merwanehamadi commented on .github/workflows/ci.yml
> +            agbenchmark start --maintain
this makes the call to the LLM

2023-07-09 23:15 UTC, merwanehamadi commented on .github/workflows/ci.yml
> +            agbenchmark start --mock --category=memory --category=code
I am testing our features by just using them

2023-07-09 23:15 UTC, merwanehamadi commented on .github/workflows/ci.yml
> +          path: agent/gpt-engineer/projects
right now I only added the logs for gpt-engineer.

2023-07-09 23:18 UTC, merwanehamadi commented on .github/workflows/ci.yml
> +          fi
I will put these into a file called: 
setup_auto-gpt.sh

and then dynamically call the right setup depending on the agent.

2023-07-10 00:25 UTC, SilenNaihin requested changes

2023-07-10 00:25 UTC, SilenNaihin commented on .github/workflows/ci.yml
> +        agent-name:
you forgot SuperAGI here

2023-07-10 00:34 UTC, SilenNaihin approved these changes

2023-07-10 01:06 UTC, merged